apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-multitool
  labels:
    app: nginx-multitool
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-multitool
  template:
    metadata:
      labels:
        app: nginx-multitool
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: /usr/share/nginx/html/index.html
          name: configmap-volume
          subPath: index.html
      - name: multitool
        image: wbitt/network-multitool
        env:
        - name: HTTP_PORT
          valueFrom:
            configMapKeyRef:
              name: multitool-configmap
              key: HTTP_PORT
        - name: HTTPS_PORT
          valueFrom:
            configMapKeyRef:
              name: multitool-configmap
              key: HTTPS_PORT
        ports:
        - containerPort: 1180
        - containerPort: 11443
      volumes:
      - name: configmap-volume
        configMap:
          name: nginx-configmap
          items:
          - key: index
            path: index.html
          
        