---
clickhouse:
  hosts:
    clickhouse:
      ansible_host: 84.201.159.183

vector:
  hosts:
    vector:
      ansible_host: 51.250.2.231

lighthouse:
  hosts:
    lighthouse:
      ansible_host: 158.160.42.144