{
 "title": "New dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Disk (available)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    { "expr": "node_filesystem_avail_bytes" }
   ]
  },
  {
   "title": "Memory (free)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    { "expr": "node_memory_MemFree_bytes", "legendFormat": "free" }
   ]
  },
  {
   "title": "CPULA (1/5/15)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "100 - (avg by (instance) (rate(node_cpu_seconds_total{mode=\"idle\"}[1m])) * 100)",
     "legendFormat": "cpula 1m"
    },
    {
     "expr": "100 - (avg by (instance) (rate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "cpula 5m"
    },
    {
     "expr": "100 - (avg by (instance) (rate(node_cpu_seconds_total{mode=\"idle\"}[15m])) * 100)",
     "legendFormat": "cpula 15m"
    }
   ]
  },
  {
   "title": "CPU (idle)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(node_cpu_seconds_total{cpu=\"0\", mode=\"idle\"}[5m])*100",
     "legendFormat": "cpu 0"
    },
    {
     "expr": "rate(node_cpu_seconds_total{cpu=\"1\", mode=\"idle\"}[5m])*100",
     "legendFormat": "cpu 1"
    }
   ]
  }
 ]
}