kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: hostpath
provisioner: microk8s.io/hostpath
reclaimPolicy: Retain
parameters:
  pvDir: /home/alex/volumes/pv1
volumeBindingMode: WaitForFirstConsumer