apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin
spec:
  type: LoadBalancer
  ports:
  - port: 80
    name: phpmyadmin
    targetPort: 8080
  # Kubernetes-метки селектора, использованные в шаблоне подов при создании объекта Deployment.
  selector:
    app.kubernetes.io/name: phpmyadmin