#cloud-config
users:
  - name: root
    groups: sudo
    shell: /bin/bash
    sudo: 'ALL=(ALL) NOPASSWD:ALL'
    ssh-authorized-keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDYswdNQz7Z8J7fiWhFvkJhkma3BSw7dSk1TEx/2H7LhhNRQVwBsWMjtHTgNMoFZn+q+XEOsAKycky17cpvntVufClyZwsxqF3TvQXh+8Mg3pNfqAxm7iRDYeaZFGqMaLUtDhwjtNesLEn3RMD0X9aguhJD1BeNOxRBaMb4TQElwuR7Gy5IExpMoEjI7N9hbnl9TjninF41SPBvJ/34ngGi9VYNuC6CquZ+rV8vLOReTsWt3MsCvHBI4wmK/B5uwRPZ3abW7RPhxOwOD/IdHNqvW2lgwOkv6mlQ9Wa7ZXxNs0vaZLusiJTbC6o/1ofKloaiaivOR5fxQPfjKribJUSY4eAcJIEzKD+0xMJDxXPRj0ILb5e4Xpgpx4lnQhGkSBmQX0QSp91gL+WHY2reI3VObUbEJ6KDulMrIdPmCPIBtsSo4u4i8X70kfjZWBukwvDCjjMsCug8sGshH9brxn3Pez6wR2KfOhXngH/7zGdJvddnyYixbSlDnmpMdwEwjrs= alex@ubuntu-22

runcmd: 
  - yum install httpd -y
  - service httpd start
  - chkconfig httpd on
  
write_files:
  - content: |
      <html><h1>My cool web-server</h1><img src="https://storage.yandexcloud.net/alex-2024-05-12/hello.png"></html>
    path: /var/www/html/index.html
    permissions: '0755'