---
- name: Install Clickhouse
  hosts: clickhouse
  gather_facts: false
  roles:
    - clickhouse-role

- name: Install Vector
  hosts: vector
  gather_facts: false
  roles:
    - vector-role

- name: Install Nginx + LightHouse
  hosts: lighthouse
  gather_facts: false
  pre_tasks:
    - name: Install Git
      become: true
      ansible.builtin.yum:
        name: git
        state: present
  roles:
    - lighthouse-role