apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: logs-describe-pods
  namespace: default
rules:
  - apiGroups: [ "" ]
    resources: [ "pods", "pods/log", "pods/describe" ]
    verbs: [ "get" ]