apiVersion: v1
kind: Service
metadata:
  name: nginx-multitool-svc
spec:
  selector:
    app: nginx-multitool
  ports:
    - name: nginx
      protocol: TCP
      port: 9001
      targetPort: 80
      nodePort: 30000
    - name: multitool
      protocol: TCP
      port: 9002
      targetPort: 8080
      nodePort: 30001
  type: NodePort