name: "App deploy APP CI/CD"

on:
  push:
    branches:
      - main
    paths:
      - '11-diplom/app/**'
    tags:
      - '*'

jobs:
  deploy:
    name: Deploy app to cluster
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to Yandex Cloud Container Registry
        id: login-cr
        uses: yc-actions/yc-cr-login@v2
        with:
          yc-sa-json-credentials: ${{ secrets.YC_SA_JSON_CREDENTIALS }}

      - name: Build, and push image to Yandex Cloud Container Registry
        if: github.event_name == 'push' && github.ref_type != 'tag'
        env:
          CR_REGISTRY: crpul4f5308ai5814ctv
          CR_REPOSITORY: app
          IMAGE_TAG: ${{ github.ref_name }}
        run: |
          docker build -t cr.yandex/$CR_REGISTRY/$CR_REPOSITORY ./11-diplom/app/docker/
          docker push cr.yandex/$CR_REGISTRY/$CR_REPOSITORY

      - name: Build, tag, and push image to Yandex Cloud Container Registry
        if: github.ref_type == 'tag'
        env:
          CR_REGISTRY: crpul4f5308ai5814ctv
          CR_REPOSITORY: app
          IMAGE_TAG: ${{ github.ref_name }}
        run: |
          docker build -t cr.yandex/$CR_REGISTRY/$CR_REPOSITORY:$IMAGE_TAG ./11-diplom/app/docker/
          docker push cr.yandex/$CR_REGISTRY/$CR_REPOSITORY:$IMAGE_TAG

      - name: Deploy app
        uses: actions-hub/kubectl@master
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG_DATA }}
          CR_REGISTRY: crpul4f5308ai5814ctv
          CR_REPOSITORY: app
          IMAGE_TAG: ${{ github.ref_name }}
        with:
          args: cat ./11-diplom/deployment/app-deployment.yaml | sed "s/latest/$IMAGE_TAG/" | kubectl apply -f ./11-diplom/deployment/ -n app